config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'youtube/index'
  root to: "youtube#index"
  get 'youtube/search'
  post 'youtube/search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname ,presence: true
end

app/models/youtube.rb
class Youtube < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/youtube_controller.rb
class YoutubeController < ApplicationController
  before_action :move_to_index, except: [:index]
  KEY1 = ENV["GOOGLE_API_KEY1"]
  KEY2 = ENV["GOOGLE_API_KEY2"]
  KEY3 = ENV["GOOGLE_API_KEY3"]
  KEY4 = ENV["GOOGLE_API_KEY4"]
  KEY5 = ENV["GOOGLE_API_KEY5"]

  GOOGLE_API_KEY = [KEY1,KEY2,KEY3,KEY4,KEY5]

  @@max_results = 3
  def find_videos(keyword ,sorting ,after_date_years ,after_date_months ,after_date_days ,before_date_years ,before_date_months ,before_date_days)
    service = Google::Apis::YoutubeV3::YouTubeService.new
    service.key = GOOGLE_API_KEY[0]
    oder = "relevance"
    case sorting
    when "1"
      oder = 'relevance'
    when "2"
      oder = 'date'
    when "3"
      oder = 'viewCount'
    when "4"
      oder = 'rating'
    end
    next_page_token = nil
    opt = {
      q: keyword,
      type: 'video',
      max_results: @@max_results,
      order: oder,
      page_token: next_page_token,
      #published_after: (5.years + 2000.days).ago.iso8601,
      published_after: after_date_years+"-"+after_date_months+"-"+after_date_days+"T00:00:00Z",
      published_before: before_date_years+"-"+before_date_months+"-"+before_date_days+"T00:00:00Z",
    }

    begin
      results = service.list_searches(:snippet, opt)
    rescue
      service.key = GOOGLE_API_KEY[1]
      begin
        results = service.list_searches(:snippet, opt)
      rescue
        service.key = GOOGLE_API_KEY[2]
        begin
          results = service.list_searches(:snippet, opt)
        rescue
          service.key = GOOGLE_API_KEY[3]
        end
      end
    end
  end

  def find_video_id(youtube_data)
    results_items = youtube_data.to_h
    videos = []

    @@max_results.times do |timesCount|
      video = results_items[:items][timesCount][:id][:video_id]
      videos << video
    end
    return videos
    #video_cnt_get = service.list_videos(:statistics, id: video_id)
      #video_cnt_get_h = video_cnt_get.to_h  
  end

  def count_videos(youtube_data_video_id)
    service = Google::Apis::YoutubeV3::YouTubeService.new
    service.key = GOOGLE_API_KEY[0]
    count_videos=[]

    begin
      @@max_results.times do |timesCount|
        video_cnt_get = service.list_videos(:statistics, id: youtube_data_video_id[timesCount])
        video_cnt_get_h = video_cnt_get.to_h
        count_videos << video_cnt_get_h
      end
    rescue
      service.key = GOOGLE_API_KEY[1]
      begin
        @@max_results.times do |timesCount|
          video_cnt_get = service.list_videos(:statistics, id: youtube_data_video_id[timesCount])
          video_cnt_get_h = video_cnt_get.to_h
          count_videos << video_cnt_get_h
        end
      rescue
        service.key = GOOGLE_API_KEY[2]
        begin
          @@max_results.times do |timesCount|
            video_cnt_get = service.list_videos(:statistics, id: youtube_data_video_id[timesCount])
            video_cnt_get_h = video_cnt_get.to_h
            count_videos << video_cnt_get_h
          end
        rescue
          service.key = GOOGLE_API_KEY[3]
          @@max_results.times do |timesCount|
            video_cnt_get = service.list_videos(:statistics, id: youtube_data_video_id[timesCount])
            video_cnt_get_h = video_cnt_get.to_h
            count_videos << video_cnt_get_h
          end
        end
      end
    end
  return count_videos
  end

  def search
    @youtube_data = find_videos(params[:keyword],params[:sorting],params["after_date(1i)"],params["after_date(2i)"],params["after_date(3i)"],params["before_date(1i)"],params["before_date(2i)"],params["before_date(3i)"])
    @youtube_data_video_id = find_video_id(@youtube_data)
    @youtube_data_count = count_videos(@youtube_data_video_id)
    @max_results = @@max_results
    @test = params[:keyword],params[:sorting],params["after_date(1i)"],params[:after_date],params[:before_date]
  end

  def index
    @max_results = @@max_results
  end

  private 

  def move_to_index
    redirect_to user_session_path unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/youtube_helper.rb
module YoutubeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YoutubeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/youtube/index.html.erb
<h1>検索内容</h1>
    <ul class='lists-right'>
      <% if user_signed_in? %>
      <li><%= current_user.nickname %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
<%= form_with(model: @youtube, url: youtube_search_path, local: true) do |form| %>
  <div class="field">
    <%= form.label :keyword, "キーワード" %>
    <%= form.text_field :keyword %>

    <%= form.label :sorting, "並び換え" %>
    <%= form.select :sorting, {'関連度順': 1, 'アップロード順': 2, '視聴回数順': 3, '評価順': 4} %>
<br>
検索範囲

      <%= raw sprintf(
                  form.date_select(
                    :after_date,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: Time.now.year,
                    end_year: (1990),
                    date_separator: '%s'),
                  " 年 ", " 月 ") + " 日から " %>
                  <br>
      <%= raw sprintf(
                  form.date_select(
                    :before_date,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: Time.now.year,
                    end_year: (1990),
                    date_separator: '%s'),
                  " 年 ", " 月 ") + " 日まで " %>
    </div>
    <br>
<p>
  <div class="actions">
    <%= form.submit "検索" %>
  </div>
<% end %>

app/views/youtube/search.html.erb
<h1>検索結果</h1>
<h1>キーワード</h1>
<%#= @youtube_data.to_h[:items][0][:snippet] %>
<%#=@youtube_data_count2%>
<%=@test%>


<%@max_results.times do |timescount|%>
  <p>タイトル<%= @youtube_data.to_h[:items][timescount][:snippet][:title] %> </p>
  <p>再生数<%=@youtube_data_count[timescount][:items][0][:statistics][:view_count]%> </p>
  <p>高評価<%=@youtube_data_count[timescount][:items][0][:statistics][:like_count]%> </p>
  <p>低評価<%=@youtube_data_count[timescount][:items][0][:statistics][:dislike_count]%> </p>
  <p>コメント数<%=@youtube_data_count[timescount][:items][0][:statistics][:comment_count]%> </p>
  <p>投稿日 <%= @youtube_data.to_h[:items][timescount][:snippet][:published_at] %> </p>
  <p>チャンネル名 <%= @youtube_data.to_h[:items][timescount][:snippet][:channel_title] %></p>
  <p>URL <%= "https://www.youtube.com/watch?v=#{@youtube_data.to_h[:items][timescount][:id][:video_id]}" %></p>
  <p>サムネURL <%= @youtube_data.to_h[:items][timescount][:snippet][:thumbnails][:high][:url] %></p>
  <div><iframe width="560" height="315" src="https://www.youtube.com/embed/<%=@youtube_data.to_h[:items][timescount][:id][:video_id]%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>

<% end %>